name: Publish to Pub.dev

on: [push, pull_request]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      # 拉取仓库代码
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      # 发布插件
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@v1.3
        with:
          # 设置发布插件需要的 Token
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}