name: Publish to Pub.dev

on: [push, pull_request]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      # 拉取仓库代码
      - name: "Checkout"
        uses: actions/checkout@v2
      - run: flutter pub get
      # 发布插件
      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}